services:
  train:
    container_name: train
    image: harbor.hiqs.de/kbl_a_m/kblam_train:en.0.1
    command: >
      --dataset datasets
      --train_dataset synthetic
      --B 20
      --gradient_accm_step 40
      --total_steps 20001
      --use_cached_embd
      --encoder_spec BigOAI
      --sep_query_head
      --kb_token_layer_frequency 3
      --use_data_aug
      --key_embd_src key
      --N 120000
      --hf_model_spec "meta-llama/Llama-3.2-1B-Instruct"
      --llm_type llama3
      --save_step 400
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - WANDB_API_KEY=${WANDB_API_KEY}
    volumes:
      - ~/.cache:/root/.cache
      - /home/julian_sammet/Documents/datadisk/experiments/kblam/exp_v0.0.16:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]