services:
  create:
    container_name: create
    image: wikidata:latest
    tty: true  
    command: >
      --size 200000
      --language de
      --worker 2
    environment:
      - WIKIDATA_API_KEY=${WIKIDATA_API_KEY}
      - WIKIDATA_PATH=${WIKIDATA_PATH}
      - WIKIDATA_MODEL_NAME=${WIKIDATA_MODEL_NAME}
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.cache:/root/.cache
      - /home/julian_sammet/Documents/repos/KBLaM-vs-Rag/KBLaM/dataset:/app/dataset